name: Scrape and Commit

on:
  schedule:
    - cron: '0 17 * * 4'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Config Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run scraping
        run: npm run scraper

      - name: Upload extracted data as an artifact
        uses: actions/upload-artifact@v6
        with:
          name: scraping-data
          path: src/db/db.json
          overwrite: true
          retention-days: 1

      - name: Save extracted data to repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/db/db.json
          git commit -m "Update database - $(date)" || echo "No changes to commit"
          git push